language: php
php: ["7.0"]
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/PluginVerifyTool.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - PluginVerifyTool PluginVerifyTool ; else true ; fi"
